Check for older guiles for g-wrap.
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/branches/1.4@4123 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5537,6 +5537,62 @@ then
   g-wrap 1.1.x will not work with this version of GnuCash." 1>&2; exit 1; }
 fi
 
+if test x$GUILE = x ; then
+	# Extract the first word of "guile", so it can be a program name with args.
+set dummy guile; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:5545: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GUILE'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$GUILE" in
+  /*)
+  ac_cv_path_GUILE="$GUILE" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_GUILE="$GUILE" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_GUILE="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_GUILE" && ac_cv_path_GUILE="no"
+  ;;
+esac
+fi
+GUILE="$ac_cv_path_GUILE"
+if test -n "$GUILE"; then
+  echo "$ac_t""$GUILE" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+ fi
+  if test "${GUILE}" = "no" ; then
+	{ echo "configure: error: g-wrap couldn't find guile." 1>&2; exit 1; }
+ fi
+ 
+       echo $ac_n "checking for whether guile uses old SMOB format""... $ac_c" 1>&6
+echo "configure:5584: checking for whether guile uses old SMOB format" >&5
+ if ${GUILE} -c '(if (string=? (version) "1.3") (exit 0) (exit 1))' ;
+ then
+	echo "$ac_t""yes" 1>&6
+        cat >> confdefs.h <<\EOF
+#define GWRAP_OLD_GUILE_SMOB 1
+EOF
+
+ else
+	echo "$ac_t""no" 1>&6
+ fi
+
+
 
 
 
@@ -5551,7 +5607,7 @@ GUILE_LINK_ARGS=""
 # Extract the first word of "guile-config", so it can be a program name with args.
 set dummy guile-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:5555: checking for $ac_word" >&5
+echo "configure:5611: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GUILE_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -5595,7 +5651,7 @@ fi
 # Extract the first word of "guile", so it can be a program name with args.
 set dummy guile; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:5599: checking for $ac_word" >&5
+echo "configure:5655: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GUILE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -5886,10 +5942,10 @@ s%@GNOME_CFLAGS@%$GNOME_CFLAGS%g
 s%@GNOME_LIBS@%$GNOME_LIBS%g
 s%@G_WRAP_CONFIG@%$G_WRAP_CONFIG%g
 s%@G_WRAP@%$G_WRAP%g
+s%@GUILE@%$GUILE%g
 s%@G_WRAP_COMPILE_ARGS@%$G_WRAP_COMPILE_ARGS%g
 s%@G_WRAP_LINK_ARGS@%$G_WRAP_LINK_ARGS%g
 s%@GUILE_CONFIG@%$GUILE_CONFIG%g
-s%@GUILE@%$GUILE%g
 s%@GUILE_COMPILE_ARGS@%$GUILE_COMPILE_ARGS%g
 s%@GUILE_LINK_ARGS@%$GUILE_LINK_ARGS%g
 
