more patches from rob
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/trunk@1400 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2287,27 +2287,29 @@ fi
 
 # Set GUILELIBS according to the set of libraries needed to link
 # with guile.
-echo $ac_n "checking for gh_enter in -lguile""... $ac_c" 1>&6
-echo "configure:2292: checking for gh_enter in -lguile" >&5
-ac_lib_var=`echo guile'_'gh_enter | sed 'y%./+-%__p_%'`
+
+# If readline exists, just assume that guile needs it.  It probably does.
+echo $ac_n "checking for readline in -lreadline""... $ac_c" 1>&6
+echo "configure:2294: checking for readline in -lreadline" >&5
+ac_lib_var=`echo readline'_'readline | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
-LIBS="-lguile  $LIBS"
+LIBS="-lreadline  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2300 "configure"
+#line 2302 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
     builtin and then its argument prototype would still apply.  */
-char gh_enter();
+char readline();
 
 int main() {
-gh_enter()
+readline()
 ; return 0; }
 EOF
-if { (eval echo configure:2311: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2313: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2322,182 +2324,130 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  GUILELIBS="$GUILELIBS -lguile"
+    ac_tr_lib=HAVE_LIB`echo readline | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-lreadline $LIBS"
+
 else
   echo "$ac_t""no" 1>&6
-echo $ac_n "checking for gh_define in -lguile""... $ac_c" 1>&6
-echo "configure:2330: checking for gh_define in -lguile" >&5
-ac_lib_var=`echo guile'_'gh_define | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lguile  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 2338 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char gh_define();
+fi
 
+
+# Have to use AC_TRY_LINK here because AC_CHECK_LIB caches the
+# results, so one failure makes all further attempts fail.
+
+echo $ac_n "checking for guile""... $ac_c" 1>&6
+echo "configure:2345: checking for guile" >&5
+
+GNC_LIBS_SAFE=${LIBS}
+
+GNC_TEST_LIBS="-lguile"
+LIBS="${LIBS} ${GNC_LIBS_HELPER} ${GNC_TEST_LIBS}"
+cat > conftest.$ac_ext <<EOF
+#line 2352 "configure"
+#include "confdefs.h"
+#include<guile/gh.h>
 int main() {
-gh_define()
+gh_eval_file;
 ; return 0; }
 EOF
-if { (eval echo configure:2349: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2359: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
+  GUILELIBS="$GUILELIBS ${GNC_TEST_LIBS}"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
 fi
 rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  GUILELIBS="$GUILELIBS -lguile -ldl -lreadline"
-else
-  echo "$ac_t""no" 1>&6
-echo $ac_n "checking for gh_eval_file in -lguile""... $ac_c" 1>&6
-echo "configure:2368: checking for gh_eval_file in -lguile" >&5
-ac_lib_var=`echo guile'_'gh_eval_file | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lguile  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 2376 "configure"
+LIBS="${LIBS_SAFE}"
+            
+if test x"${GUILELIBS}" == x;
+then
+  GNC_TEST_LIBS="-lguile -lqthreads"
+  LIBS="${LIBS} ${GNC_LIBS_HELPER} ${GNC_TEST_LIBS}"
+  cat > conftest.$ac_ext <<EOF
+#line 2374 "configure"
 #include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char gh_eval_file();
-
+#include<guile/gh.h>
 int main() {
-gh_eval_file()
+gh_eval_file;
 ; return 0; }
 EOF
-if { (eval echo configure:2387: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2381: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
+  GUILELIBS="$GUILELIBS ${GNC_TEST_LIBS}"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
 fi
 rm -f conftest*
-LIBS="$ac_save_LIBS"
-
+  LIBS="${LIBS_SAFE}"
 fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  GUILELIBS="$GUILELIBS -lguile -ltermcap"
-else
-  echo "$ac_t""no" 1>&6
-echo $ac_n "checking for gh_eval_file in -lguile""... $ac_c" 1>&6
-echo "configure:2406: checking for gh_eval_file in -lguile" >&5
-ac_lib_var=`echo guile'_'gh_eval_file | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lguile -ldl -lreadline -ltermcap $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 2414 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char gh_eval_file();
 
+if test x"${GUILELIBS}" == x;
+then
+  GNC_TEST_LIBS="-lguile -ltermcap"
+  LIBS="${LIBS} ${GNC_LIBS_HELPER} ${GNC_TEST_LIBS}"
+  cat > conftest.$ac_ext <<EOF
+#line 2397 "configure"
+#include "confdefs.h"
+#include<guile/gh.h>
 int main() {
-gh_eval_file()
+gh_eval_file;
 ; return 0; }
 EOF
-if { (eval echo configure:2425: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2404: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
+  GUILELIBS="$GUILELIBS ${GNC_TEST_LIBS}"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
 fi
 rm -f conftest*
-LIBS="$ac_save_LIBS"
-
+  LIBS="${LIBS_SAFE}"
 fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  GUILELIBS="$GUILELIBS -lguile -ldl -lreadline -ltermcap"
-else
-  echo "$ac_t""no" 1>&6
-echo $ac_n "checking for gh_eval_file in -lguile""... $ac_c" 1>&6
-echo "configure:2444: checking for gh_eval_file in -lguile" >&5
-ac_lib_var=`echo guile'_'gh_eval_file | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lguile -ldl -lreadline -ltermcap -lqthreads $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 2452 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char gh_eval_file();
 
+if test x"${GUILELIBS}" == x;
+then
+  GNC_TEST_LIBS="-lguile -lqthreads -ltermcap"
+  LIBS="${LIBS} ${GNC_LIBS_HELPER} ${GNC_TEST_LIBS}"
+  cat > conftest.$ac_ext <<EOF
+#line 2420 "configure"
+#include "confdefs.h"
+#include<guile/gh.h>
 int main() {
-gh_eval_file()
+gh_eval_file;
 ; return 0; }
 EOF
-if { (eval echo configure:2463: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2427: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
+  GUILELIBS="$GUILELIBS ${GNC_TEST_LIBS}"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
 fi
 rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  GUILELIBS="$GUILELIBS -lguile -ldl -lreadline -ltermcap -lqthreads"
-else
-  echo "$ac_t""no" 1>&6
-{ echo "configure: error: cannot link with guile" 1>&2; exit 1; }
+  LIBS="${LIBS_SAFE}"
 fi
 
-fi
-
-         -ltermcap
-fi
-
-      -ldl -lreadline
-fi
-
-   
+if test x"${GUILELIBS}" == x;
+then
+  { echo "configure: error: Cannot link with guile.  Do you have guile 1.3 installed?" 1>&2; exit 1; }
 fi
 
 
 
+
+echo "$ac_t""yes" 1>&6
 
 ### Plotutils
 
 echo $ac_n "checking for openpl in -lplot""... $ac_c" 1>&6
-echo "configure:2501: checking for openpl in -lplot" >&5
+echo "configure:2451: checking for openpl in -lplot" >&5
 ac_lib_var=`echo plot'_'openpl | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2505,7 +2455,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lplot $X_PRE_LIBS $MOTIF_LIBS $X_EXTRA_LIBS -lXaw $X_LIBS $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2509 "configure"
+#line 2459 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2516,7 +2466,7 @@ int main() {
 openpl()
 ; return 0; }
 EOF
-if { (eval echo configure:2520: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:2470: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2698,10 +2648,8 @@ trap 'rm -fr `echo "Makefile
           src/Makefile
           src/engine/Makefile
           src/guile/Makefile
-          src/guile/gnucash.h
           src/scm/Makefile
           src/scm/startup/Makefile
-          src/scm/startup/init.scm
           src/gnome/Makefile
           src/motif/Makefile
           src/qt/Makefile
@@ -2812,10 +2760,8 @@ CONFIG_FILES=\${CONFIG_FILES-"Makefile
           src/Makefile
           src/engine/Makefile
           src/guile/Makefile
-          src/guile/gnucash.h
           src/scm/Makefile
           src/scm/startup/Makefile
-          src/scm/startup/init.scm
           src/gnome/Makefile
           src/motif/Makefile
           src/qt/Makefile
@@ -3006,3 +2952,7 @@ test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
 
 
 chmod +x gnucash
+
+make -f Makefile.config.finish prefix=${prefix} \
+                               GNC_SHAREDIR=${GNC_SHAREDIR} \
+                               GNC_CONFIGDIR=${GNC_SHAREDIR} 
