need to have guile
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/trunk@1341 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2367,7 +2367,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   GUILELIBS="-lguile -ldl -lreadline -lqthreads"
 else
   echo "$ac_t""no" 1>&6
-echo "configure: warning: cannot link with guile" 1>&2
+{ echo "configure: error: cannot link with guile" 1>&2; exit 1; }
 fi
 
 fi
