Allow building from either SVN or SVK - create gnc-svnversion script that builds the revision number   from either SVN or SVK.  The script should fail gracefully if   you don't have SVK installed - convert the configure script to use the new gnc-svnversion script - convert the splash-screen Makefile to use the gnc-svnversions script
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/trunk@14427 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/src/gnome-utils/Makefile.am b/src/gnome-utils/Makefile.am
--- a/src/gnome-utils/Makefile.am
+++ b/src/gnome-utils/Makefile.am
@@ -264,15 +264,10 @@ gnc-svninfo.h: _gnc-svninfo.h
 	-rm -f _gnc-svninfo.h
 
 _gnc-svninfo.h: Makefile
-	@s=${srcdir} ; \
-	if [ -h ${srcdir}/Makefile.am ] ; then \
-		d=`readlink $(srcdir)/Makefile.am` ; \
-		s="${srcdir}/`dirname $$d`" ; \
-	fi ; \
-	if [ -d $$s/.svn ] ; then \
-		svninfo=`svnversion $$s` ; \
+	@svninfo=`${top_srcdir}/util/gnc-svnversion ${srcdir}` ; \
+	if [ $$? = 0 ] ; then \
 		if [ -z "$$svninfo" ] ; then \
-			echo "svnversion failed.  figure out why." ; \
+			echo "gnc-svnversion failed.  figure out why." ; \
 			echo "can't determine svn revision from $$s." ; \
 			exit 1 ; \
 		fi ; \
