* src/gnome-utils/Makefile.am: exit if "svn info" fails.
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/trunk@12008 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/src/gnome-utils/Makefile.am b/src/gnome-utils/Makefile.am
--- a/src/gnome-utils/Makefile.am
+++ b/src/gnome-utils/Makefile.am
@@ -321,6 +321,11 @@ gnc-svninfo.h: .gnc-svninfo.h
 	fi ; \
 	if [ -d $$s/.svn ] ; then \
 		svninfo=`svn info $$s |grep '^Revision: '|sed 's/Revision: //'` ; \
+		if [ -z "$$svninfo" ] ; then \
+			echo "svn info failed.  figure out why." ; \
+			echo "can't determine svn revision from $$s." ; \
+			exit 1 ; \
+		fi ; \
 		echo "#define GNUCASH_SVN_REV $$svninfo" > gnc-svninfo.h ; \
 	fi
 
