bug fixes
git-svn-id: svn+ssh://svn.gnucash.org/repo/gnucash/trunk@2470 57a11ea4-9604-0410-9ed3-97b8803252fd

diff --git a/src/optional/swig/Makefile.am b/src/optional/swig/Makefile.am
--- a/src/optional/swig/Makefile.am
+++ b/src/optional/swig/Makefile.am
@@ -73,7 +73,8 @@ install-data-local: libgncswig.la
 	elif [ -f ${perllibdir}/libgncswig.so.1.1 ]; then \
 		cd ${perllibdir} && ln -s libgncswig.so.1.1 gnucash.so; \
 	else \
-		echo "Can't find libgncswig shared library!"; \
+		echo "Can't find libgncswig shared library!" \
+		exit 1; \
 	fi
 
 uninstall-local:
